project:
  type: book
  output-dir: "docs"
  
execute:
  echo: false
  warning: false
  output: asis

book:
  title: "Inducción"
  subtitle: "Unidad de Psicometría y Análisis de Datos (PAD) - Mide UC"
  author: "Tom Baladrón"
  date: "7/17/2025"
  sidebar:
    search: true
    style: floating
    collapse-level: 1
    border: true
  repo-url: https://github.com/psynguin/InduccionUA
  page-footer: 
    border: false
    background: light
    left: | 
      Libro escrito por Tom Baladrón
    right: |
      Este libro fue construido con <a href="https://quarto.org/">Quarto</a>.

  chapters:
    - index.qmd
    - 00.1. sobre el autor.qmd
    - 00.2. agradecimientos.qmd
    - part: Módulo teórico
      chapters: 
        - 1.01.1 Matematico.qmd
        - 1.01.2 Matematico2.qmd
        - 1.01.3 Matematico3.qmd
        - 1.02. Estandares.qmd
        - 1.03. Psicometría.qmd
        - 1.04. Teoría Clásica.qmd
        - 1.05. IRT.qmd
    - part: Módulo código
      chapters: 
        - 2.01. R base.qmd
    - part: Módulo PAD
      chapters: 
        - 3.01. Introduction.qmd
    - references.qmd

bibliography: references.bib

number-sections: true
number-depth: 2

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual